### ISSUE TITLE
background gradient for textboxes

### ISSUE THREAD

**Issue by futurepaul** [futurepaul/fluttermint#14]
<img width="355" alt="Screen Shot 2022-06-25 at 10 22 15 AM" src="https://user-images.githubusercontent.com/543668/175784164-03b46645-2ffc-4f4a-aeee-550348007a2a.png">

<img width="357" alt="Screen Shot 2022-06-25 at 10 23 38 AM" src="https://user-images.githubusercontent.com/543668/175784196-77ef8e37-9adc-4d18-bf11-a3c0b2f56c18.png">

I customized a text field here not too hard:
https://github.com/BitcoinDevShop/pln/blob/master/mobile/lib/widgets/text_field.dart

**Comment by justinmoon** [comment]
Did we do this?
