### ISSUE TITLE
Can't do HTTPS

### ISSUE THREAD

**Issue by justinmoon** [futurepaul/fluttermint#37]
![image](https://user-images.githubusercontent.com/4335621/187988860-f046d067-6950-4ed4-8603-25488587448f.png)

**Comment by justinmoon** [comment]
This is the "connect info" to attempt to join `{"members":[[0,"wss://fmssl.sirion.io:443"]],"max_evil":0}`

**Comment by futurepaul** [comment]
have you tried it from a browser and it works?

**Comment by justinmoon** [comment]
So far only tried from Android.

**Comment by futurepaul** [comment]
not sure it's an app problem or a self-signed cert problem

**Comment by justinmoon** [comment]
Yea I'll look into this one

**Comment by Maan2003** [comment]
> have you tried it from a browser and it works?

Yes, it works.
