### ISSUE TITLE
DB not getting saved properly

### ISSUE THREAD

**Issue by justinmoon** [futurepaul/fluttermint#59]
From @elsirion:

> Seems the app doesn't always save the DB? Closed it and lost the last tx in the list. Validated by spending all coins and there being a double spend.

![image](https://user-images.githubusercontent.com/4335621/191134049-b8204948-8a56-4043-a3d5-cdfe47dfa00c.png)

**Comment by elsirion** [comment]
Mostly fixed by #607. The client should also migrate to a more robust DB like rocksdb.

**Comment by justinmoon** [comment]
Yup I think we can close. Thanks for fixing this!
