### ISSUE TITLE
Replace qr_code_scanner with mobile_scanner

### ISSUE THREAD

**Issue by prusnak** [futurepaul/fluttermint#78]
According to https://pub.dev/packages/qr_code_scanner:

> Since the underlying frameworks of this package, [zxing for android](https://github.com/zxing/zxing) and [MTBBarcodescanner for iOS](https://github.com/mikebuss/MTBBarcodeScanner) are both not longer maintaned, this plugin is no longer up to date and in maintenance mode only. Only bug fixes and minor enhancements will be considered.
>
> I am developing a new plugin [mobile_scanner](https://pub.dev/packages/mobile_scanner) that uses the latest version of MLKit for detecting barcodes and QR codes. On Android it also uses the latest version of CameraX, and on iOS the native AVFoundation for best camera performance.

Also mobile_scanner supports macOS which is not supported by qr_code_scanner

**Comment by justinmoon** [comment]
Done! https://github.com/futurepaul/fluttermint/pull/83

**Comment by prusnak** [comment]
Closed in https://github.com/futurepaul/fluttermint/pull/83
