### ISSUE TITLE
Poll invoices we have generated to detect incoming payments

### ISSUE THREAD

**Issue by justinmoon** [futurepaul/fluttermint#9]
Should we do this in `minimint-bridge` or should something like `UserClient` provide this?

Eventually we should just subscribe to a websocket or something. But initially we'll probably do polling ...

**Comment by futurepaul** [comment]
setup a poll "stream" with riverpod in the pln project: https://github.com/BitcoinDevShop/pln/blob/bd7ea130185c9163414fa7dbc49ab035a050e60c/mobile/lib/screens/channel_status.dart

I'm sure it could be improved but it works pretty well for my purposes
